export default [
    "Can You Pass The GRAPHQL Test?",
    "How To Turn Your GRAPHQL From Zero To Hero",
    "You Will Thank Us - 10 Tips About GRAPHQL You Need To Know",
    "27 Ways To Improve GRAPHQL",
    "How I Improved My GRAPHQL In One Easy Lesson",
    "How I Improved My GRAPHQL In One Day",
    "Best GRAPHQL Android/iPhone Apps",
    "Find A Quick Way To GRAPHQL",
    "Here's A Quick Way To Solve A Problem with GRAPHQL",
    "Your Key To Success: GRAPHQL",
    "Some People Excel At GRAPHQL And Some Don't - Which One Are You?",
    "GRAPHQL And The Chuck Norris Effect",
    "The Ugly Truth About GRAPHQL",
    "Take 10 Minutes to Get Started With GRAPHQL",
    "Secrets To GRAPHQL – Even In This Down Economy",
    "Top 25 Quotes On GRAPHQL",
    "The Truth About GRAPHQL In 3 Minutes",
    "Here Is A Quick Cure For GRAPHQL",
    "There’s Big Money In GRAPHQL",
    "5 Best Ways To Sell GRAPHQL",
    "GRAPHQL Your Way To Success",
    "How You Can (Do) GRAPHQL In 24 Hours Or Less For Free",
    "If You Want To Be A Winner, Change Your GRAPHQL Philosophy Now!",
    "Wondering How To Make Your GRAPHQL Rock? Read This!",
    "Get Rid of GRAPHQL For Good",
    "Why GRAPHQL Is No Friend To Small Business",
    "Open The Gates For GRAPHQL By Using These Simple Tips",
    "9 Ways GRAPHQL Can Make You Invincible",
    "7 Ways To Keep Your GRAPHQL Growing Without Burning The Midnight Oil",
    "Does GRAPHQL Sometimes Make You Feel Stupid?",
    "How To Make Your GRAPHQL Look Amazing In 5 Days",
    "GRAPHQL Expert Interview",
    "2 Things You Must Know About GRAPHQL",
    "5 Easy Ways You Can Turn GRAPHQL Into Success",
    "Avoid The Top 10 Mistakes Made By Beginning GRAPHQL",
    "How GRAPHQL Made Me A Better Salesperson",
    "GRAPHQL An Incredibly Easy Method That Works For All",
    "Everything You Wanted to Know About GRAPHQL and Were Afraid To Ask",
    "Fascinating GRAPHQL Tactics That Can Help Your Business Grow",
    "3 Ways You Can Reinvent GRAPHQL Without Looking Like An Amateur",
    "3 Ways To Have (A) More Appealing GRAPHQL",
    "10 Unforgivable Sins Of GRAPHQL",
    "17 Tricks About GRAPHQL You Wish You Knew Before",
    "How To Make Your GRAPHQL Look Like A Million Bucks",
    "How To Get (A) Fabulous GRAPHQL On A Tight Budget",
    "Short Story: The Truth About GRAPHQL",
    "Make Your GRAPHQLA Reality",
    "Why You Never See GRAPHQL That Actually Works",
    "How To Start A Business With GRAPHQL",
    "Don't Be Fooled By GRAPHQL",
    "World Class Tools Make GRAPHQL Push Button Easy",
    "3 Ways Create Better GRAPHQL With The Help Of Your Dog",
    "Are You Embarrassed By Your GRAPHQL Skills? Here's What To Do",
    "3 Ways Twitter Destroyed My GRAPHQL Without Me Noticing",
    "If You Do Not (Do)GRAPHQL Now, You Will Hate Yourself Later",
    "5 Secrets: How To Use GRAPHQL To Create A Successful Business(Product)",
    "How To Win Clients And Influence Markets with GRAPHQL",
    "GRAPHQL: The Samurai Way",
    "Revolutionize Your GRAPHQL With These Easy-peasy Tips",
    "How To Save Money with GRAPHQL?"
]